Repository CS2113-AY1819S1-T13-5/main, pull requests merged in 2018-10, with the labels that each got.

#84 Fix AddCommandTest
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.bug

#144 Change Logic of Recommend
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/RecommendCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RecommendCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/RecommendArguments.java
  src/main/java/seedu/address/model/WorkoutBook.java
  src/main/java/seedu/address/model/workout/UniqueWorkoutList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.high, type.enhancement

#149 Add Tests
  src/main/java/seedu/address/logic/parser/RecommendCommandParser.java
  src/main/java/seedu/address/model/RecommendArguments.java
  src/test/java/seedu/address/logic/commands/RecommendCommandTest.java
  src/test/java/seedu/address/logic/parser/RecommendCommandParserTest.java
Labels: priority.high, type.task

#151 Update Calories REGEX to [0,1000]
  docs/UserGuide.adoc
  src/main/java/seedu/address/model/workout/Calories.java
  src/main/java/seedu/address/model/workout/Duration.java
  src/test/java/seedu/address/logic/commands/RecommendCommandTest.java
  src/test/java/seedu/address/logic/parser/RecommendCommandParserTest.java
  src/test/java/seedu/address/ui/WorkoutListPanelTest.java
Labels: priority.high, type.task

#155 Update Recommend command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ModifyCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ModifyCommandParser.java
  src/main/java/seedu/address/logic/parser/RecommendCommandParser.java
  src/main/java/seedu/address/model/ProfileWindowManager.java
  src/main/java/seedu/address/model/workout/Difficulty.java
  src/main/java/seedu/address/model/workout/Duration.java
  src/main/java/seedu/address/model/workout/Equipment.java
  src/main/java/seedu/address/model/workout/Instruction.java
  src/main/java/seedu/address/model/workout/Muscle.java
  src/main/java/seedu/address/model/workout/Name.java
  src/main/java/seedu/address/model/workout/Remark.java
  src/main/java/seedu/address/model/workout/Type.java
  src/main/java/seedu/address/model/workout/UniqueWorkoutList.java
  src/test/java/seedu/address/logic/commands/RecommendCommandTest.java
  src/test/java/seedu/address/logic/parser/RecommendCommandParserTest.java
Labels: priority.medium, type.task

#159 Update CurrentCommand
  .travis.yml
  build.gradle
  docs/HelpWindow.html
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/CurrentCommand.java
  src/main/java/seedu/address/logic/parser/ModifyCommandParser.java
  src/main/java/seedu/address/model/ProfileWindowManager.java
  src/main/java/seedu/address/ui/ProfileWindow.java
  src/main/resources/htmlFiles/ProfileWindow.html
  src/test/java/seedu/address/ui/ProfileWindowTest.java
Labels: priority.high, type.enhancement
